### ISSUE TITLE
Transitions will be changhed between sections a page 

### ISSUE THREAD

**Issue by AlexeyKorkoza** [pub-t/plain-destination#25]
Bug. 
If many letters is in block then arrow of down is on the text, under not it.
Screenshot: 
![screenshot from 2016-06-23 12-58-32](https://cloud.githubusercontent.com/assets/11200149/16299305/3dd2cfe4-3942-11e6-851d-367594419ea5.png)

**Comment by AlexeyKorkoza** [comment]
I need examples of transitions between the blocks on the HTML page because my current solution is very bad. I find yet a bug.
I click to rotate screen twice in dev tools a google chrome when I am on second block. After I get next result:
![screenshot from 2016-06-23 16-27-19](https://cloud.githubusercontent.com/assets/11200149/16305328/01b8c520-3962-11e6-9b51-46809e2d9d3b.png)
I push this code in my branch. Name of branch is arrows. 
Help me.

**Comment by irnc** [comment]
Closing as this is not relevant to our needs. Please prototype mobile UI for our case, we don't need such big text.
