### ISSUE TITLE
Решить проблему с запуском двух скриптов для precommit

### ISSUE THREAD

**Issue by Vanish404** [pub-t/plain-destination#26]
Нужно запустить два скрипта одновременно eslint и htmllint с помощью npm-пакета husky, т.е. какой результат скрипта будет?
  ```
  "lint": "eslint .",
  "precommit": "npm run lint",
  "htmllint": "htmllint .html"
```

**Comment by irnc** [comment]
You should not run both scripts _using husky_, you should run both on `precommit`. Please loot at https://www.npmjs.com/package/concurrently as an option to solve your issue.

**Comment by Vanish404** [comment]
Done #29
