### ISSUE TITLE
Align text input and button

### ISSUE THREAD

**Issue by irnc** [pub-t/plain-destination#6]
See https://www.dropbox.com/s/nko0bjt5wwo6lim/Untitled.png?dl=0

**Comment by AlexeyKorkoza** [comment]
This issue may close ?

**Comment by irnc** [comment]
It may be closed, if it was fixed. In this case there should be a reference to pull request fixing it.

**Comment by AlexeyKorkoza** [comment]
https://github.com/pub-t/plain-destination/pull/24
