### ISSUE TITLE
Use unobtrusive JavaScript for listening on events from form

### ISSUE THREAD

**Issue by irnc** [pub-t/plain-destination#7]
See https://en.wikipedia.org/wiki/Unobtrusive_JavaScript

**Comment by KrivichaninDenis** [comment]
Изменил [js-файл](https://github.com/pub-t/plain-destination/blob/master/js/script.js) и [html](https://github.com/pub-t/plain-destination/blob/master/index.html) под ненавязчивый js.

**Comment by irnc** [comment]
А как же процесс с pull request и ревью?

**Comment by KrivichaninDenis** [comment]
Я нечаянно в мастера запушил( хотя и ветку создал..

**Comment by irnc** [comment]
Вот коммит на ревью https://github.com/pub-t/plain-destination/commit/fd424981569aa070a9405297ad2111cea8df21a0
